### ISSUE TITLE
Documentation for session API

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/nativescript-background-http#184]
Looking at the readme and I see this line repeated a few times:

```
var session = bghttp.session("image-upload");
```

However, I do not see this documented. My assumption is that:

* Each time you do an HTTP call, you will use a new session. 
* The name of the session ... is what? Used for descriptive purposes? Must it be unique? 

Basically, can you add documentation for what session() means?

**Comment by lini** [comment]
Documenting exactly what the session constructor does is a tricky subject, since the internal implementation for Android and iOS is very different. For Android it is only used to keep track of the active sessions and to stop an upload in progress. For iOS it is passed to the native `NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier` method which returns a native object with the session config. 

To answer your questions: each session must have a unique identifier, but you can create more than one task and upload multiple files (at the same time) using one session. The demo applications in this repo can be used to test this behavior.

**Comment by cfjedimaster** [comment]
I think that's fair (that it is difficult to answer), but even this text here was helpful. I see it's closed - can it be reopened and added to the readme?

**Comment by cfjedimaster** [comment]
Ah sorry - didn't see - thank you!
