### ISSUE TITLE
get uploaded image url back

### ISSUE THREAD

**Issue by alzizoomar** [NativeScript/nativescript-background-http#230]
i uploaded image successfully how to get it back from server as url

**Comment by DimitarTodorov** [comment]
Hi @alzizoomar 
The plugin provides a functionality to upload files to a server. The request you are posting here is about server functionality. You have to implement a functionality on your server which fills the data of the response. Another way is to add an endpoint of your server in order to call it and observe the desired information. 
Regards,
NativeScript Team

**Comment by HugoAntares** [comment]
Hi @DimitarTachev 
I do receive properly my file but I can't get any data from `e.response` in my task complete event. Where can I get the data returned by the server in my NS app ?

**Comment by DimitarTachev** [comment]
@HugoAntares,

I suppose you've tried to mention @DimitarTodorov ;)

**Comment by HugoAntares** [comment]
@DimitarTachev indeed, my bad ^^

And actually I thought I'll get the server response in the complete event, but there is a responded event. My bad, again!
